mkdir -p templates/{patients,traitements,beneficiers,chambres,consultations,commandes,lignes_commandes,medicaments,plaintes,lunettes,prescriptions_lunettes,prescriptions_medicales,produits,grades_med,soignants,interners,consommers,depenses}
touch templates/base.html
touch templates/patients/{patient_list.html,patient_detail.html,patient_form.html,patient_confirm_delete.html}
touch templates/traitements/{traitement_list.html,traitement_detail.html,traitement_form.html,traitement_confirm_delete.html}
touch templates/beneficiers/{beneficier_list.html,beneficier_detail.html,beneficier_form.html,beneficier_confirm_delete.html}
touch templates/chambres/{chambre_list.html,chambre_detail.html,chambre_form.html,chambre_confirm_delete.html}
touch templates/consultations/{consultation_list.html,consultation_detail.html,consultation_form.html,consultation_confirm_delete.html}
touch templates/commandes/{commande_list.html,commande_detail.html,commande_form.html,commande_confirm_delete.html}
touch templates/lignes_commandes/{ligne_commande_list.html,ligne_commande_detail.html,ligne_commande_form.html,ligne_commande_confirm_delete.html}
touch templates/medicaments/{medicament_list.html,medicament_detail.html,medicament_form.html,medicament_confirm_delete.html}
touch templates/plaintes/{plainte_list.html,plainte_detail.html,plainte_form.html,plainte_confirm_delete.html}
touch templates/lunettes/{lunette_list.html,lunette_detail.html,lunette_form.html,lunette_confirm_delete.html}
touch templates/prescriptions_lunettes/{prescription_lunette_list.html,prescription_lunette_detail.html,prescription_lunette_form.html,prescription_lunette_confirm_delete.html}
touch templates/prescriptions_medicales/{prescription_medicale_list.html,prescription_medicale_detail.html,prescription_medicale_form.html,prescription_medicale_confirm_delete.html}
touch templates/produits/{produit_list.html,produit_detail.html,produit_form.html,produit_confirm_delete.html}
touch templates/grades_med/{grade_med_list.html,grade_med_detail.html,grade_med_form.html,grade_med_confirm_delete.html}
touch templates/soignants/{soignant_list.html,soignant_detail.html,soignant_form.html,soignant_confirm_delete.html}
touch templates/interners/{interner_list.html,interner_detail.html,interner_form.html,interner_confirm_delete.html}
touch templates/consommers/{consommer_list.html,consommer_detail.html,consommer_form.html,consommer_confirm_delete.html}
touch templates/depenses/{depense_list.html,depense_detail.html,depense_form.html,depense_confirm_delete.html}
