# Generated by Django 5.1.1 on 2024-12-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospial", "0002_facture_lignefacture"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="libelle",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
