# Generated by Django 5.1.1 on 2024-12-06 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospial", "0004_alter_lignecommande_commande"),
    ]

    operations = [
        migrations.AddField(
            model_name="consommer",
            name="facture",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consommations",
                to="hospial.facture",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consultation",
            name="facture",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultations",
                to="hospial.facture",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interner",
            name="facture",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="internements",
                to="hospial.facture",
            ),
        ),
        migrations.AlterField(
            model_name="lignefacture",
            name="facture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lignes_facture",
                to="hospial.facture",
            ),
        ),
    ]
